kafka-ui:
  container_name: kafka-ui
  image: provectuslabs/kafka-ui:latest
  volumes:
    - ./kafka-ui/config.yml:/etc/kafkaui/dynamic_config.yaml
  environment:
    DYNAMIC_CONFIG_ENABLED: 'true'
  depends_on:
    - kafka-0
    - kafka-1
  networks:
    - kafka
  ports:
    - '8080:8080'
  healthcheck:
    test: wget --no-verbose --tries=1 --spider localhost:8080 || exit 1
    interval: 5s
    timeout: 10s
    retries: 3
    start_period: 30s
